server:
  port: 8083
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.188.25:9300
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    virtual-host: /leyou
    username: leyou
    password: leyou
    host: 192.168.188.25
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
